name: yug_app
description: "语光世界平台移动端"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 网络请求
  dio: ^5.4.1
  grpc: ^3.2.4
  protobuf: ^3.1.0

  # 基础组件
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  package_info_plus: ^4.2.0
  shared_preferences: ^2.2.2
  adaptive_theme: ^3.4.1
  ducafe_ui_core: ^1.0.6
  intl: ^0.19.0

  # UI 组件
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  validatorless: ^1.2.3
  pinput: ^5.0.0
  flutter_easyloading: ^3.0.5
  salomon_bottom_bar: ^3.3.2
  curved_navigation_bar: ^1.0.6
  wave_transition: ^0.0.6
  animated_button_bars: ^0.0.1+1
  flutter_screenutil: ^5.9.0
  flutter_markdown: ^0.7.5
  photo_view: ^0.15.0
  pull_to_refresh: ^2.0.0
  lottie: ^2.7.0
  rive: ^0.12.4
  flutter_local_notifications: ^18.0.1

  # 功能组件
  path_provider: ^2.1.2
  device_info_plus: ^11.3.0
  image_picker: ^1.0.7
  uuid: ^4.2.2
  sqflite: ^2.3.2
  image_cropper: ^5.0.1
  aliyun_push_flutter: ^1.2.3
  go_router: ^14.8.1
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.8
  icons_launcher: ^3.0.0

# app 图标配置
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_ios.png"
  image_path_android: "assets/icons/launcher_android.png"
  adaptive_icon_background: "#ffffff"

# 启动图配置
flutter_native_splash:
  color: "#8C9EFF"
  image: "assets/launcher/background.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/svgs/
    - assets/launcher/
    - assets/icons/
